# Generated by Django 3.0.5 on 2020-09-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0002_motionactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MotionActivity',
        ),
    ]
