# Generated by Django 3.0.5 on 2020-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0003_motionactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=20),
        ),
    ]
