# Generated by Django 3.0.5 on 2020-09-16 16:53

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0007_auto_20200916_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('slug', models.CharField(max_length=20, null=True)),
                ('restingMinutes', djongo.models.fields.JSONField(blank=True, default=list, null=True)),
                ('activityPerDay', models.IntegerField(null=True)),
                ('walkPerWeek', models.IntegerField(null=True)),
            ],
        ),
    ]
